apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xbuildservers.example.org
spec:
  group: example.org
  names:
    kind: XBuildServer
    plural: xbuildservers
  claimNames:
    kind: BuildServer
    plural: buildservers
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              instance-type:
                type: string